[tool.pyrefly]
pythonVersion = "3.9"
pythonPlatform = "Darwin"
extraPaths = [
  "/Users/abhishekmeena/Library/Python/3.9/lib/python/site-packages",
  "/Library/Python/3.9/site-packages",
  "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages"
]
reportMissingImports = "none"
reportMissingModuleSource = "none"
typeCheckingMode = "off"

[tool.pyright]
pythonVersion = "3.9"
pythonPlatform = "Darwin"
extraPaths = [
  "/Users/abhishekmeena/Library/Python/3.9/lib/python/site-packages",
  "/Library/Python/3.9/site-packages",
  "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages"
]
reportMissingImports = "none"
reportMissingModuleSource = "none"
typeCheckingMode = "off"
